### ISSUE TITLE
[1.29] Add links to the CoW Swap menu

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1254]
Add link to [Grants ](https://grants.cow.fi/) to the menu
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/f13eba9d-d0d8-41a3-b422-4bf434dcbdae)

Also, would be great to add links to: 
 - [Security portal](https://app.chainpatrol.io/cow)
 - Audits 
![image](https://user-images.githubusercontent.com/70885163/203354661-9138dab3-2752-4530-aafd-d13da600b9c0.png)
 - Explorer app

**Comment by anxolin** [comment]
Great! Let's do it. 

Also, we need to add a link back to cow.fi (Alex M suggested), maybe even to the explorer too?

**Comment by anxolin** [comment]
> Overview -> Audit 1, Audit 2

@avsavsavs  @fairlighteth, maybe instead of having the two links, we could have a shield icon, saying Security Audits with a link to cow.fi where we show all the audits? (just to prevent this to grow out of control)

Actually, this new page could have some content to re-assure users and explain what to expect in terms of security

**Comment by anxolin** [comment]
> We have a task to add Grants to Explorer https://github.com/cowprotocol/explorer/issues/243 , so we can update the description and add more links there


Yes, it would be great to improve it too
