### ISSUE TITLE
MPS price is incorrect on Limit orders page

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1759]
1. Connect to a GC network
2. Open Limit orders page
3. Specify a token pair: MPS-WXDAI
4. Check the USD estimation

**AR**: price is off
![price.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/0ae774d2-c0b7-46e8-8f24-4f218a4f3c84)
Compare with Swap page:
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/0e2e2938-3bca-4ddc-b7a0-6909635724fc)

**ER**: price should be normal

**Comment by elena-zh** [comment]
Another issue with this MPS token is fees calculation for Buy and Sell token. You can see details here https://discord.com/channels/869166959739170836/869170873033166868/1053717559972724776

**Comment by nlordell** [comment]
> Another issue with this MPS token is fees calculation for Buy and Sell token:

This is an unfortunate issue with the MPS token and stems from a few things:
- MPS has 0 decimals, meaning the smallest indivisible unit of MPS is 1.0, and is worth ~10$
- Fees are always (at the smart contract level) taken from the sell token.

If you put these two together, and assume some small trading fees (lets use 0.05$ on Gnosis Chain for example), then you see why the problem happens: we try and compute 0.05$ in MPS, which is 0.005 MPS. We need to round to the smallest divisible unit, meaning we can either choose 0 (meaning we would subsidize trading this token completely) or 1 (which is worth 10$ in fees instead of the expected 0.05$).

As a general rule, we always round up with fees, which is very unfortunate for users selling MPS (note that this doesn't affect buying MPS because the fees are taking in the sell token in the smart contract).

Changing this requires some pretty big changes to our fee model.

**Comment by nlordell** [comment]
It looks to me that the native price computation is normalizing the price for base units.

Specifically, the `token/0x.../native_price` returns a factor such that `10**18 wei(TOKEN) == native_price xDAI == native_price * 10**18 wei(xDAI)`. In other words, `native_price` is **not** normalized for token decimals.

For the MPS native price, we are returning `9090909090909091000`. Noting that `MPS.decimals == 0` (meaning that `wei(MPS) == 1.0 MPS`), and applying the formula we get:
```
10**18 wei(MPS) = 9090909090909091000 xDAI
10**18 MPS = 9090909090909091000 xDAI
1.0 MPS = 9090909090909091000/10**18 xDAI
1.0 MPS = 9.090909 xDAI
```

Which is reasonable. I wonder if this is related to the USDC issue we were seeing before, and the fix that is in place doesn't work for 0-decimal tokens.

**Comment by nlordell** [comment]
Also, looking at the `/quote` requests they seem reasonable:

**Request:**
```json
{
  "sellToken":"0xfa57AA7beED63D03Aaf85fFd1753f5f6242588fb",
  "buyToken":"0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d",
  "from":"0x0000000000000000000000000000000000000000",
  "receiver":"0xdBC682D0eC19bd276Fd6C2af4E0189B584BB31E1",
  "appData":"0x487B02C558D729ABAF3ECF17881A4181E5BC2446429A0995142297E897B6EB37",
  "partiallyFillable":false,
  "kind":"sell",
  "sellAmountBeforeFee":"10"
}
```

**Response:**
```json
{
  "quote":{
    "sellToken":"0xfa57aa7beed63d03aaf85ffd1753f5f6242588fb",
    "buyToken":"0xe91d153e0b41518a2ce8dd3d7944fa863463a97d",
    "receiver":"0xdbc682d0ec19bd276fd6c2af4e0189b584bb31e1",
    "sellAmount":"9",
    "buyAmount":"87668933141096763961",
    "validTo":1671477715,
    "appData":"0x487b02c558d729abaf3ecf17881a4181e5bc2446429a0995142297e897b6eb37",
    "feeAmount":"1",
    "kind":"sell",
    "partiallyFillable":false,
    "sellTokenBalance":"erc20",
    "buyTokenBalance":"erc20",
    "signingScheme":"eip712"
  },
  "from":"0x0000000000000000000000000000000000000000",
  "expiration":"2022-12-19T18:52:55.283814279Z",
  "id":13954073
}
```

Here we have buy amount 10 MPS costs 87.668933 xDAI which is reasonable as well.

**Comment by anxolin** [comment]
Wow, thanks for digging so deep @nlordell! 
We will take a look to this. 

> As a side note, I also saw a request from the FE selling 90909090909090911114509850340067488682 MPS which, at 10$ a pop is ~1e39 - 25 orders of magnitude more than the combined world GDP in 2022, so not really a valid trade.

Lol! 😂
