### ISSUE TITLE
Sometimes weird decimals inside the 'receive (including fees)' popup

### ISSUE THREAD

**Issue by charlesndalton** [cowprotocol/cowswap#1794]
Full disclosure I didn't read through the 425 open issues before creating this issue so it may be a duplicate

For some tokens and amounts, the popup that gets opened when you hover over the question mark next to 'Receive (incl. fee)' formats the decimals in a way that deceives the eye. Below is an example.

<img width="194" alt="Screen Shot 2022-12-23 at 11 32 20 AM" src="https://user-images.githubusercontent.com/95452384/209399037-0dcb8cd8-73d0-497a-a159-a96587f92b62.png">

Taking a quick look at this, it looks like you're going to be paying nearly all of your tokens into fees, and it's only when you notice that the decimals are aligned differently that you see that this is not the case

Possible solutions:
- always align to 4 decimals, extending with 0s at the end if needed
- always align the bottom number's number of decimals to the top numbers', or vice versa

**Comment by anxolin** [comment]
Thanks @charlesndalton , that's a fair point

We will put it in the backlog since seems fairly easy to solve and if it misled you, it can mislead others. 
We can't promise when we will be starting this one. 

If you are very eager to have it, and since I have the intuition that you are an engineer, we would love to invite you to make a little contribution to the project. We will happily review it. Note how everything is Open Source here. 

Cheers!

**Comment by fairlighteth** [comment]
@elena-zh This has been addressed I believe in 1.29.0 ?

**Comment by elena-zh** [comment]
Hey @fairlighteth , no. 
It was added there, then reverted. 
See https://cowservices.slack.com/archives/C0361CDG8GP/p1674120302892629?thread_ts=1674044011.727939&cid=C0361CDG8GP
![image](https://user-images.githubusercontent.com/70885163/214256560-0c1a8c6f-5b7e-46ea-9a54-ed498f9acf9c.png)
