### ISSUE TITLE
Custom slippage around 5% reverts for some values to a lower value

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#20]
**Describe the bug**
When setting a custom slippage around 5% a wrong notification is shown for some values

**How to Reproduce**
1. Go to settings
2. Set custom value between 5.00 - 5.1% in 0.01% steps
4. See error for 5.02% and 5.06% - `Enter a valid slippage percentage`

**Expected behavior**
`Your transaction may be frontrun should` be shown

**Screenshots**
<img width="316" alt="Bildschirmfoto 2021-04-08 um 11 02 38" src="https://user-images.githubusercontent.com/34510341/114000077-f0d68000-985a-11eb-8b3e-3bca4d0f5fa8.png">
<img width="325" alt="Bildschirmfoto 2021-04-08 um 11 02 32" src="https://user-images.githubusercontent.com/34510341/114000091-f59b3400-985a-11eb-9e4a-7809c01168bd.png">
<img width="320" alt="Bildschirmfoto 2021-04-08 um 11 02 47" src="https://user-images.githubusercontent.com/34510341/114000102-f764f780-985a-11eb-802e-5659f30c5f18.png">
...
<img width="317" alt="Bildschirmfoto 2021-04-08 um 11 02 58" src="https://user-images.githubusercontent.com/34510341/114000117-faf87e80-985a-11eb-91b0-358a04ce8074.png">

> Original issue https://github.com/gnosis/cowswap/issues/395 by @MareenG

**Comment by alfetopito** [comment]
This is javascript being javascript dealing with floats:

Printing the same value thru all the steps we take from user input to internal value

When the float is multiplied by 100... it doesn't go so well

![Screenshot 2022-12-28 at 14 57 07](https://user-images.githubusercontent.com/43217/209830852-ea50481e-cb0a-4cd9-9221-c3148c68ed43.png)

Using `round` instead of `floor` works a little better

![Screenshot 2022-12-28 at 15 01 24](https://user-images.githubusercontent.com/43217/209831406-ae4fc5e1-2400-42b9-9817-d815439c2aa1.png)
