### ISSUE TITLE
Receive amount is different when refresh the page

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2125]
Reported based on user's issue https://cowservices.slack.com/archives/C03NXGFJA2U/p1678288217781959

1. Open CoW Swap, Swap page
2. Select HEX-USDC token pair
3. Select 500 000 HEX to sell
4. Check the Receive amount
![before the refresh.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/ded1e76d-63bd-4365-8686-4adbdb564ab3)

5. Refresh the page
6. Check the receive amount once again

**AR**: The amount is a way less than the 1st amount

![lower.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/6e3fa167-2f97-4a37-bb04-0e15db166559)

**ER**: amounts should be the same. No need to refres the page or retype into the fields amouts to trade in order to get a correct price

**Comment by anxolin** [comment]
Mmm, that's bad. Looks like a race condition. Maybe we are returning the "fast-quote" after the "normal-quote"...

**Comment by anxolin** [comment]
I don't think that is what I mention above. So maybe is a race condition in the backend? I can reproduce even by following the steps above, and just waiting. It's like, randomly I sometimes I get a good price, and sometimes I get a bad one. 

Compare these 2 responses. They were done very close to each other, however the `Buy Tokens` estimation is very different.

I can share the HAR file to see these request (I will share in slack, since GH don't allow me to easily paste it here)

Request 1:
![Screenshot at Mar 08 16-56-32](https://user-images.githubusercontent.com/2352112/223779344-4a14a16b-0e8f-40ee-b919-78f1b007b8a5.png)

Response 1:
![Screenshot at Mar 08 16-56-16](https://user-images.githubusercontent.com/2352112/223779405-36beefb4-ddc3-45ca-83f4-69ace7d1fe38.png)


Request 2:
![Screenshot at Mar 08 16-57-07](https://user-images.githubusercontent.com/2352112/223779207-7143b99a-1566-42c6-aae7-83660d60910b.png)

Response 2:
![Screenshot at Mar 08 16-56-55](https://user-images.githubusercontent.com/2352112/223779251-1c692ca6-f75f-4632-a989-7e731814d1ce.png)

**Comment by elena-zh** [comment]
No longer reproducible
