### ISSUE TITLE
Rabby wallet: app sets incorrect TX type when change accounts

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2366]
Reported in https://cowservices.slack.com/archives/C036G0J90BU/p1682407446079979

The issue is related to the Rabby wallet that supports importing accounts from EOA wallets (MM) and SC wallets (Safe and other)

**To reproduce:** 
1. Install Rabby wallet
2. Import MM account there
3. Connect (import) a Safe account to the wallet
4. Connect to the CowSwap: select a SC account
5. Place an order
6. Switch to any EOA account inside of the Rabby wallet
7. Try placing an order 

**AR**: setPreSignature transaction is set (e.g. user need to pay gas for the transaction)
The issue remains to be reproducible until a user refreshes the page
![change accounts.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/6ae9fb15-317e-485b-b300-52a207461339)

**ER**: sign order should be![should be.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/5bb62e9e-d46e-4bf0-8cae-618058218492)

**Comment by anxolin** [comment]
@elena-zh I checked and im not sure this has to do with changing wallets. For me its not detecting that is a safe even without changing. This happens also for SWAP

The issue is that right now we base our detection that it is a safe in what Wallet Connect reports. We don't have any detections implemented to decide if it is a safe based only on the address. 

This is more involved, so I put it in pause.

**Comment by elena-zh** [comment]
One more case: when change SC wallet to EOA inside the Rabby, the app behaves like connected to a SC-wallet.
**Steps:** 

1. Connect with a Safe address
2. On rabby, switch to an EOA account
3. Ui remains thinking it's still a Safe

Refreshing helps to resolve this. 
![image](https://github.com/cowprotocol/cowswap/assets/70885163/c2b2196e-a1cb-4bae-ae24-9a29fa2decab)
