### ISSUE TITLE
[1.37.1] Limit price does not match the price a user specified

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2514]
Some details are in https://cowservices.slack.com/archives/C0361CDG8GP/p1684770146776229

1. Place an limit order of WETH/USDC on Mainnet at price of 1850
2. Check the limit price in the Your orders table

**AR**: the price is not exactly 1850
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/e4a4637f-f8fa-426c-8433-bcea1ccbab1d)

**ER**: the price should be exactly 1850

**Comment by anxolin** [comment]
I believe it is not exactly 1500 because the order needs to be expressed in a fraction, meaning we will need to express it in how much I buy given an amount of sell tokens. 

It might be not possible given the amounts to get an "Exact fraction" and this is what happens here.

Most of the time, the rounding will make it so it matches. 
It is a bit improbable the part where in the widget we show 1850 as the price of the order when is not the case. Probably, we should even do the rounding up always in the user's favor so they get always at least what they type in the price, and not slightly less. 

However, this is a change that if we do, we should set some time for it. I will leave it out of the version 1.38

**Comment by anxolin** [comment]
I tested it, if the 4 decimals of precision would be 9s, it would have round up and then we would remove the zeros. 

In your case, it's expected behavior because the recession of the 4 decimals let us present the number as you have in your screenshot (basically reflects reality)

<img width="1675" alt="image" src="https://github.com/cowprotocol/cowswap/assets/2352112/adaa6d95-d916-4b79-a997-1e92cb9483e5">

**Comment by elena-zh** [comment]
Closing: no users' complaints on it.
