### ISSUE TITLE
Uncheck 'Modify' box when change Safes/Networks

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2684]
Related to #2669

1. Open Safe wallet and make sure that you have at least 2 Safe accounts in different networks 
2. Make sure that fallback handler is not set up in each saje (how to reset it you can find in #2568)
3. Load CoW Swap app
4. Open Advanced orders page
5. Specify an order, check 'Modify' box
6. Then change Safe account (the CoW Swap app is still displayed on the screen): 
 ![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/9dcd2cf1-c0f3-4735-bf0c-f12eb48d1edc)
8. Specify an order on the Advanced orders page

**AR**:  'Modify' box is already checked in the form
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/62fd8e12-93b0-4eab-8990-492fec7f5e0c)
**ER**: Modify box is unchecked.
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/bcbfa987-e07c-4731-9cd9-3fa9c76d32c7)

**Comment by nenadV91** [comment]
This doesn't seem to happen anymore because right now when you change the Safe Account, the safe will reload the whole iFrame app (CowSwap in our case) and you will be sent on Swap page by default. Once you go back to advanced order tab, and select the tokens, the modify handler checkbox will be unchecked.
