### ISSUE TITLE
2440/uni merge: request to switch network is not sent after a wallet connection

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#340]
Related to #2536

1. Open the app
2. Select Rinkeby network (or any other)
3. Make sure that Rinkeby is not selected in the MM (f.e. GC)
4. Connect to the MM wallet

**AR**: the app is connected to GC, no request to switch network to Rinkeby

**ER**: request to change a network to Rinkeby is sent to MM right after conneciton

> Original issue https://github.com/gnosis/cowswap/issues/2627 by @elena-zh

**Comment by elena-zh** [comment]
I have to reopen the issue. Due to the issue is still here: When 'Gnosis Chain' (f.e.) is selected in the network selector, and when I press on the Connect wallet button, I'm not connected to Gnosis Chain network, but to the network that is selected in the connected wallet (in my case, to Rinkeby). 
And there is no request to connect to GC after the wallet connection. 
See the video: https://watch.screencastify.com/v/jSK61uDnt6oqk9DDITMx

**Comment by anxolin** [comment]
I'm not sure about this one. So when you connect it takes the network from the connected wallet. Only if you change it later it CowSwap it will require the change in MM.

I can see arguments why your proposal is better for some cases, but in some others maybe I would prefer to make my wallet ditacte the network and not the other way around. 

This is currently the behaviour in Uniswap, so for now I wouldn't change it unless we get some strong feedback

**Comment by elena-zh** [comment]
@anxolin , the issue is created due to it works this way in our Cowswap app in Prod now. So the behavior will be changed after Uni merge goes live. 
But anyways, we can close this issue and leave it as it is.

**Comment by anxolin** [comment]
Okay, anyways, thanks for rising it. It was a good option, but I think as it is, is good enough, and is the lesser effort for the team
