### ISSUE TITLE
Classic ETH flow is broken when a token requires approval

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#3421]
**The issue is described for a situation when a traded amount < approved amount. 
But it appears that it is impossible to proceed with the classic ETH flow when traded WETH amount > approved amount (indeed requires approval).** 
![image](https://github.com/cowprotocol/cowswap/assets/70885163/d6584291-b9b6-42b9-b2b7-a31367ea2aba)
---------------------------------

**How to Reproduce**
1. Approve WETH token partially (e.g. 1 WETH)
2. Make sure that WETH balance is less than 0.5 (otherwise please unwrap it)
3. Specify a token pair: 0.5 ETH per any other token
4. Switch to Classic WETH flow and Wrap ETH to WETH

**AR**: when a token is wrapped, 'Approve' token modal appears. However, there is no need in approving token as trading balance is less than an approved token. 
BE shows an error when press on Approve

**Expected behavior**
No need to approve a token if trading amount < approved amount. 
A Confirm Swap modal should appear after Wrap modal

**Screenshots**
![no need in approval - enough](https://github.com/cowprotocol/cowswap/assets/70885163/f3adbb1f-ac18-4ff4-aa12-2eff3144e76f)
![not working](https://github.com/cowprotocol/cowswap/assets/70885163/9f59f33d-aa3d-422f-924f-5c9fe930f073)

**Comment by alfetopito** [comment]
I have identified what is the source of problems for the classic eth flow.

It all boils down to the Derived Swap Info 

https://github.com/cowprotocol/cowswap/blob/1cdfa24c6448e3ebf2c6e3c986cb5d7bfd269aa4/apps/cowswap-frontend/src/modules/swap/hooks/useSwapCurrenciesAmounts.ts#L13

The app relies on that to fill in the wrap info. More specifically, the input amount.
Since it's wrapping without any form, the value is `undefined`, which short circuits the whole logic down the line.

**Comment by alfetopito** [comment]
Debugging, I can see that, but the start of the flow, the value is populated.
This is where the amount to wrap here comes from:

![image](https://github.com/cowprotocol/cowswap/assets/43217/bb386bba-f582-4e2c-8303-d356d8fc6ada)

My assumption right now is that I need to store the amount into the eth flow state to have it persisted in the next steps

https://github.com/cowprotocol/cowswap/blob/f6f4e4d0b143c4ecb056269facf2f26bce638b19/apps/cowswap-frontend/src/modules/swap/state/EthFlow/ethFlowContextAtom.ts#L21
