### ISSUE TITLE
2440/uni merge: gas amount always shows 37

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#350]
Related to #2536

1. Open the app
2. Connect to the Mainnet
3. Check the gas price at the bottom of the page

**AR**: always shows 37

ER: should show gas amount on sending TX on L1 from https://etherscan.io/gastracker

> Original issue https://github.com/gnosis/cowswap/issues/2640 by @elena-zh

**Comment by alfetopito** [comment]
Couple of points regarding the gas price:
1. Not very precise, as it takes hours to update and might not be relevant for current gas spikes
2. It's fetched from an onchain contract, and that's why I believe it's not updated very often
3. Is only available on mainnet. Doesn't make much sense on other networks anyway

So, we either change how it's updated or it's a `won't fix`

**Comment by W3stside** [comment]
this is also the case in uniswap, low prio
