### ISSUE TITLE
Tokens from other chains may be displayed in a token list

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#3841]
I face this issue from time to time. 

I can't find a way to reproduce this and a reason that might cause this, but from time to time I start seeing the next message
![image](https://github.com/cowprotocol/cowswap/assets/70885163/6382fe99-d144-411d-9568-08fff41a1bdf)

And it happens due to tokens from other chains appear in the token list 
![image](https://github.com/cowprotocol/cowswap/assets/70885163/883c7cd2-4a06-467b-9f24-6cf8247cc8b4)
![image](https://github.com/cowprotocol/cowswap/assets/70885163/e0ff0651-5d16-4a88-8827-a52245c2d9ba)

My local storage: 
[1 (15).txt](https://github.com/cowprotocol/cowswap/files/14261941/1.15.txt)

**Comment by elena-zh** [comment]
Should be fixed in #3841

**Comment by elena-zh** [comment]
The issue is reopened due to became reproducible again. See in https://cowservices.slack.com/archives/C0361CDG8GP/p1710845080905739

![image](https://github.com/cowprotocol/cowswap/assets/70885163/22fa4b01-2fcf-4071-a7b4-634c2f4e7e3e)

**Comment by alfetopito** [comment]
I suspect this happens because when we add custom tokens, we get it from an atom rather than as input or from the token itself https://github.com/cowprotocol/cowswap/blob/9cd4bf53807e307c213c547c762907b71bb5b343/libs/tokens/src/state/tokens/userAddedTokensAtom.ts#L24

Changing this to rely on the token info instead should prevent the issue in the future, but I also don't know how to trigger this behaviour in the first place.

We should also add a migration to clean the state and not lose user added tokens.
