### ISSUE TITLE
[Permittable] Fix Gnosis Chain issues

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#3860]
Every token bridged from mainnet should be permittable. e.g. GNO, COW, …

However, they are not being detected as such.

https://cowservices.slack.com/archives/C036MD8ADMG/p1707948432080889

**Comment by alfetopito** [comment]
I think I found where the problem is, but not 100% sure what's causing it.

Take for instance the [COW](https://gnosisscan.io/address/0x177127622c4a00f3d409b75571e12cb3c8973d3c#readProxyContract) token

Checking on block explorers, (etherscan or blockscout), the `version` method returns `1`.

![Image](https://github.com/cowprotocol/cowswap/assets/43217/b7e5ac91-21d9-4868-bc7d-12dbb0bf0706)
![Image](https://github.com/cowprotocol/cowswap/assets/43217/eb2617ce-9736-4f8d-aa37-1e036813406b)

However, the returned value from [1inch utils lib we use](https://github.com/1inch/permit-signed-approvals-utils/blob/b190197a45c3289867ee4e6da93f10dea51ef276/src/eip-2612-permit.utils.ts#L332) returns `2`.

![Image](https://github.com/cowprotocol/cowswap/assets/43217/7d111e53-3955-48b6-b041-0b53a115cc8f)

This is why it fails the token permit test. The call reverts since the signature doesn't match as it expects a `1`.
Forcing `1` results the token as being permittable as expected.

---

Going back to the `getTokenVersion` method, when I simulate the exact callData (`0x54fd4d50`, which is the method `version`) used by it internally, I get the value of `1` as desired: https://www.tdly.co/shared/simulation/7bcf2121-7882-4f09-b048-7e96845bcc07

The `ethCall` response for the same thing when debugging is `0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000013100000000000000000000000000000000000000000000000000000000000000`

The lib [takes the fist 65 chars](https://github.com/1inch/permit-signed-approvals-utils/blob/b190197a45c3289867ee4e6da93f10dea51ef276/src/eip-2612-permit.utils.ts#L352), which is `0x000000000000000000000000000000000000000000000000000000000000002` === 2.

No clue as to why it's returning such value.
