### ISSUE TITLE
[1.62] Connection issues when switch between modes in the configurator

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#3999]
Reported in https://cowservices.slack.com/archives/C0361CDG8GP/p1709652925895909?thread_ts=1709652627.835889&cid=C0361CDG8GP

1. connect to the wallet in the Standalone mode in the configurator
2.  switch to the Dapp mode, change a network in the MM (if the app requires)

**AR**: the configurator acts like I'm not connected, but shows balances 
![image](https://github.com/cowprotocol/cowswap/assets/70885163/c5df45e4-2c79-4194-8e18-1fa4ce30debf)
When I press on the connect button, no request is sent to MM
![image](https://github.com/cowprotocol/cowswap/assets/70885163/e9dc250c-e769-45b1-8b09-69f86101fa26)

**ER**: 2 options:
1. let a user to reconnect OR
2. show a connected state

**Comment by anxolin** [comment]
Elena, you are right there's something strange, but is related to this other issue we reported here https://github.com/cowprotocol/cowswap/issues/3892

These 2 modes are not meant to be used as you are using them. Each app will pick, one or the other, but we won't be switching like we allow to do in the configurator. For this reason, I think although there's an issue, is not too severe and will be fixed as soon as we improve our web3 provider implementations.

The underlying cause is, you have 2 competing providers:
- The widget tries to autoconnect using the injected provider, which has permission to connect since you connected before
- The Dapp also has its own connect button, so it will pass the connection to the user

The solution is, when we are in dapp mode, we should prevent the injected provider to connect. I hope this will be trivial once #3892 is implemented

**Comment by anxolin** [comment]
Is this solved by @alfetopito PR https://github.com/cowprotocol/cowswap/pull/4181?

**Comment by elena-zh** [comment]
This is not reproducible in #4181 :)
