### ISSUE TITLE
Test the filter empty URL param hook

### ISSUE THREAD

**Issue by W3stside** [cowprotocol/cowswap#412]
Based on:

Wouldn't it break anything else in the app?
I mean, it must have had a reason to be added, right?

_Originally posted by @alfetopito in https://github.com/cowprotocol/cowswap/pull/406#discussion_r850347921_

We should test if we need this. Currently removed to allow updating URL with chain ID to work

**Comment by henrypalacios** [comment]
@alfetopito I have reviewed the modifications and I see that we have only lost the ability to delete the `referral` URL parameter when it is empty. This was added so that when a user deletes the `referral` param in URL it doesn't get an invalid code notification. :point_down: 
![Selection_513](https://user-images.githubusercontent.com/4270166/165752803-720c31ac-a49b-45cd-9c11-6f32a0bd02b8.png)

I'm not sure if the **referral** flow is still maintained, but if we want to maintain the removal of this **URL parameter**, perhaps we can still use the [`useFilterEmptyQueryParams`](https://github.com/cowprotocol/cowswap/blob/develop/src/custom/hooks/useFilterEmptyQueryParams.ts#L18) hook but with a `whiteList[]`  of parameters to maintain compatibility with future parameters that are added. .

**Comment by alfetopito** [comment]
As mentioned during the call yesterday, let's try to keep this hook behaviour as you suggest: only delete from the URL the parameters that we want. 
Probably now that the `chain` is always in the URL this was causing the crash loop David saw
