### ISSUE TITLE
[safe] app does not detect batching

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#4126]
1. Open the app inside the Safe or connect to Safe using WC
2. Create ant TX (wrap/order/etc)
3. Instead of signing, app the TX to batch

**AR**: the app shows the waiting modal (no changes when a TX is signed in the bundle)
![image](https://github.com/cowprotocol/cowswap/assets/70885163/175a9942-889f-44eb-b4d1-1b4de8230a03)

**ER**: it would be great to track TXs from batch

**Comment by anxolin** [comment]
This one is related to the issue @shoom3301 was fixing?

**Comment by alfetopito** [comment]
You fixed this, right @anxolin

**Comment by anxolin** [comment]
> You fixed this, right @anxolin

I don't think so. I believe this is related to using the "batching" button from the safe. What I fixed is bundling of transactions in the safe.

This issue can be reviewed in next spring, but basically, the issue is that the SDK don't inform the Dapp about the fact we added the tx to a bundle. So CoW Swap keeps waiting

We should review with the Safe how to tackle this.
