### ISSUE TITLE
Appzi questionary is displayed when limit orders are locked

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#4635]
Reported in https://cowservices.slack.com/archives/C0361CDG8GP/p1719232323972629 
1. Open dev.swap.cow fi
2. Place some limit orders there
3. Go to Barn.cow.fi
4. Clear out your local storage there
5. Connect to a wallet
6. Open limit orders
7. wait a bit

**AR**: Appzi questionary is displayed when limit orders are locked
![image](https://github.com/cowprotocol/cowswap/assets/70885163/00d4ccb4-6fd2-4bdc-8891-fc6028f37f07)

**ER**: don't show Appzi questionary when lock screen is displayed

**Comment by anxolin** [comment]
But for this you need to go from cow.fi to barn. I wouldn't solve this, i see very low impact. Besides, I assume is doing it because the connected wallet is the same. So the user must have unlock it somewhere else, so technically they tried limit orders

Maybe, we should just ask Mindy if we can remove or reduce the appearance of this form, I think has been for a bit and is best to not bother too much the users. These forms are annoying

**Comment by elena-zh** [comment]
> But for this you need to go from cow.fi to barn.

Not necessary. I noticed that sometimes the lock screen appears after a new release applie, so users may face this issue. 
For me it is annoying to see this modal  above the screen when I was going to press on the Unlock button.
