### ISSUE TITLE
No rejection pop-ups when cancel signing transactions in WC wallets

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#643]
1. Connect to a wallet using WC option (1Inch, Gnosis Safe, etc)
2. Send a swap/onchain transaction to the connected wallet 
3. Cancel signing/reject the transaction

**AR**: there is no rejection pop-ups when cancel signing transactions in WC wallets

**AR related to the #630 issue:** event is recorded as 'Signing error' instead of the 'Reject' transaction

**ER**: 'User rejected signing the order' pop-up should appear,  'Reject' transaction event should be recorded into the GA
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/03ad09da-2754-458c-a4bf-886e55f01409)

**Comment by anxolin** [comment]
This is a great catch @elena-zh ! 

I need to review why is the case, because in principle we should capture this error and send some analytics.

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/2352112/172215185-b65af8e8-9d2c-4db2-b4dc-a64a91e15ac1.png">


I'll review tomorrow

**Comment by elena-zh** [comment]
Fixed in #655
