### ISSUE TITLE
Missleading wording

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#86]
**Description**
<img width="215" alt="Bildschirmfoto 2021-07-29 um 09 42 13" src="https://user-images.githubusercontent.com/34510341/127453873-c5bbe925-5d1a-4863-8bde-aa02e637a262.png">
Here we state **incl. gas fees** but when clicking on the tooltip we say **no gas fees.** 
I understand that this would highlight that there are no more additional gas fees. But from the first impression this is contradicting with our communication  that there are no gas fees

> Original issue https://github.com/gnosis/cowswap/issues/1096 by @MareenG

**Comment by elena-zh** [comment]
Hey @anxolin , @fairlighteth , could you please take a look into the enhancement and clarify if we are going to fix this?

**Comment by fairlighteth** [comment]
I think the reason the label `Fees (incl. gas costs)` is used, is to explicitly mention that the user won't incur any additional costs to place the order.

At the same time, the actual execution/settlement of the order does incur transaction costs. These are substracted from the SELL (or BUY?) token. As @anxolin mentions saying `no gas fees` might be misleading then.

The actual cost of settling/executing the order, to my understanding, isn't known upfront. So we can't communicate this.
We do know that placing a SELL order for an ERC-20 token is a signed (no gas) transaction.

**Suggestion:**
- Change `Fees (incl. gas costs)` to => `Fees` or `Execution fees`
- As for the tooltip, instead of saying that gas costs are free, we could say somewhere at the bottom => `Fees cover all costs to execute your order` or something similar. 
<img width="222" alt="Screen Shot 2022-04-21 at 13 42 46" src="https://user-images.githubusercontent.com/31534717/164460364-d923dd07-2f95-4042-8ec5-55d6e2d2b3f0.png">

**Comment by anxolin** [comment]
For the record, this is Mareen comment. She has a point, although its a bit tricky.

Michel explained very well. Sound good to me, Maybe Mindy (i don't know her handle) wants to chime in.

**Comment by MindyCoW** [comment]
I'm here. =) This is an issue that's come up in user testing, and I plan to tackle it as part of the narrative overhaul. We don't plan to use "gas-free" anymore in any context.
