### ISSUE TITLE
Test ShapeShift in Production

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#956]

**Comment by elena-zh** [comment]
Hey @anxolin , I have done a round of testing of the app. 
I will start my feedback from list of issues reported before https://docs.google.com/document/d/18assgdbgCmHT6v56bJRMxRi_Hk2-gpUIEGBOAsHGF8w/edit?usp=sharing

Cases 5, 8, 10 and 13 are fixed there. Case 6 is partially fixed, due to the price is still loading, but I constantly see error message at the top.

What is left, and what is important to note now: 
1. I still see that ShapeShift provides different prices, even if I quote the same amounts in parallel in 2 apps
![quotes at the same time- diff price](https://user-images.githubusercontent.com/70885163/186438587-1ce900d5-7caf-4623-84a5-007792aca182.jpg)
2. Fee is displayed in different currency in CowSwap and in the ShapeShift
![fee in cow-weth](https://user-images.githubusercontent.com/70885163/186438813-198efa6f-ff24-4edd-89f5-9b7727bd7e35.jpg)
3. Slippage is not included into the Min Received amount (case 12 from the doc above), and it still affects Surplus calculation, amounts displaying in the Account modal
![no clipp](https://user-images.githubusercontent.com/70885163/186439415-ac5311df-fa6b-4302-8977-e43df3387785.jpg)
![min received](https://user-images.githubusercontent.com/70885163/186439459-89366a49-2c3d-4f60-b0e1-6d969dc8ad88.jpg)
4. When I sign an order, button goes to the pending state, and there is no link to Explorer at least to track the order. Just pending button until the TX is filled
![the order is cancelled](https://user-images.githubusercontent.com/70885163/186439896-8032c09b-18ea-4594-ad7d-81f1b4f9c77a.jpg)
5. The order might expire/can be cancelled. I cancelled an order and did not receive any response in ShapeShift: just hanging pending button, even when I quit the form, it was still displayed until I reloaded the app
![canc - still pending](https://user-images.githubusercontent.com/70885163/186440319-eed246d1-b2ab-4ad3-8772-0524320fcef7.jpg)
![cancelled](https://user-images.githubusercontent.com/70885163/186440324-c612c0e3-df4d-4ac1-b6c2-ce8e244607ae.jpg)
6. When an order is executed, there is the link to Etherscan only, but no link to Explorer details
7. The app does not allow to place a Buy order: they are recognized as Sell only
![image](https://user-images.githubusercontent.com/70885163/186443612-a8783557-4202-47ca-87bf-57eb4b849e92.png)
8. Rounding issue reported in the case 4 in the doc above lead to the 'absence of the discount' issue: I specified a trade to have 1000 COW in the wallet to have a discount of 5%, but after a trade I got a bit less than 1000 COW in the wallet  :(
![image](https://user-images.githubusercontent.com/70885163/186445463-40355dd6-f0e6-4d4f-92ae-50743ea8f75c.png)
![image](https://user-images.githubusercontent.com/70885163/186446139-77c73dca-d7cc-4695-8d06-2096eff94f0c.png)

Thanks!
